# Generated by Django 4.2.11 on 2024-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Pound'), ('USD', 'Dollar'), ('EUR', 'Euro')], default='GBP', max_length=3),
        ),
    ]
