# Generated by Django 4.2.11 on 2024-04-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_moneyrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneyrequest',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='moneyrequest',
            old_name='requester',
            new_name='sender',
        ),
    ]
