# Generated by Django 4.2.11 on 2024-04-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_rename_receiver_moneyrequest_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrequest',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
